package net.worldwizard.support.scripts.game;

public enum GameActionCode {
    NONE, MESSAGE, SOUND, SHOP, MOVE, END_GAME, MODIFY, DELETE_SCRIPT, RANDOM_CHANCE, BATTLE, DECAY, REDRAW, LEVEL_CHANGE, SWAP_PAIRS, ADD_TO_SCORE, RELATIVE_LEVEL_CHANGE;
}
